### ISSUE TITLE
How to Pass the access token as Bearer Token

### ISSUE THREAD

**Issue by Lone-Wolf17** [zgid123/passport-google-oauth-token#15]
How does one pass the access token as Bearer token. 

It is mentioned that this package inspired by [passport-facebook-token](https://github.com/drudge/passport-facebook-token/tree/master).  This is possible in passport-facebook-token but I cant see how to do this in this package

**Comment by zgid123** [comment]
I see. Haven't used that case. Lemme add it

**Comment by zgid123** [comment]
@Lone-Wolf17 I have published  a version 1.0.7, it will fix your problem. But I still not add unit test for that because when import chai from typescript, it will raise error. And I still not find a alternative for `chai-http`. So plz test using `nestjs` example from this package or test using your own project

**Comment by zgid123** [comment]
@Lone-Wolf17 it seems there is no other issue, so I will close this one. Feel free to reopen or open another issue if you have any problem
